name: Python application

on:
  schedule:
    - cron: '0 */3 * * *'

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Configure environment variables
      run: |
        echo "AIRVISUAL_API_KEY=${{ secrets.AIRVISUAL_API_KEY }}" > .env
        echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
        echo "SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" >> .env
    - name: Run script
      run: |
        python main.py
